# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

name: "Build Sealed Bootable Container images"

env:
  REGISTRY_GHCR: "ghcr.io/${{ github.repository_owner }}"
  REGISTRY_QUAY: "quay.io"
  REPO_NAME: "${{ github.event.repository.name }}"

on:
  push:
    branches:
      - "main"
    paths:
      - "Containerfile"
      - "scripts/**"
      - ".github/workflows/bootable-containers.yml"
  # We will need a distinct workflow for pull request builds as we will not
  # have access to secrets for signing in those.
  # pull_request:
  #   branches:
  #     - "main"
  schedule:
    - cron: "0 4 * * MON"
  workflow_dispatch:

# Allow:
# - Read access to the repo content
# - Write access to packages to allow access to GitHub container registry
permissions:
  contents: "read"
  packages: "write"
  id-token: "write"

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: "blacksmith-4vcpu-ubuntu-2404"
    strategy:
      fail-fast: false
      matrix:
        variant: ["silverblue"]
        release: ["44"]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Blacksmith workaround"
        run: mkdir $HOME/.docker

      - name: Remove unwanted software
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9

      - name: Mount BTRFS for podman storage
        id: container-storage
        uses: ublue-os/container-storage-action@dc1f4c8f17b672069e921f001132f7cf98a423a6
        continue-on-error: true
        with:
          target-dir: /var/lib/containers
          mount-opts: compress-force=zstd:2
          loopback-free: "1"

      - name: "Runner setup"
        uses: travier/bootc-dev-actions/bootc-ubuntu-setup@main

      - name: "Login to Container Registry (ghcr.io)"
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /tmp/storage-run-0/containers/auth.json

      - name: "Generate version"
        id: version
        run: |
          set -euxo pipefail
          version="$(date '+%Y%m%d.0')"
          echo "Using version: ${version}"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: "Get Secure Boot signing key"
        run: |
          mkdir -p /tmp/keys
          printenv SB_KEY > /tmp/keys/key
          printenv SB_CRT > /tmp/keys/crt
        env:
          SB_KEY: ${{ secrets.SB_KEY }}
          SB_CRT: ${{ secrets.SB_CRT }}

      - name: "Build kernel container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-kernel
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }}
          containerfiles: Containerfile.kernel
          oci: true
          build-args: |
            BASE=quay.io/fedora-ostree-desktops/${{ matrix.variant }}:${{ matrix.release }}.${{ steps.version.outputs.version }}

      - name: "Build base container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-base
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }}
          containerfiles: Containerfile.base
          oci: true
          build-args: |
            BASE=quay.io/fedora-ostree-desktops/${{ matrix.variant }}:${{ matrix.release }}.${{ steps.version.outputs.version }}
            SYSTEMDBOOT=${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/systemd-boot:${{ matrix.release }}
          extra-args: |
            --skip-unused-stages=false
            --security-opt=label=disable
            --volume ${{ github.workspace }}:/run/src

      - name: "Build Generic UKI container image"
        uses: redhat-actions/buildah-build@v2
        if: false
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}
          containerfiles: Containerfile.uki
          oci: true
          build-args: |
            BASE=${{ env.REPO_NAME }}/${{ matrix.variant }}-base:${{ matrix.release }}.${{ steps.version.outputs.version }}
            KERNEL=${{ env.REPO_NAME }}/${{ matrix.variant }}-kernel:${{ matrix.release }}.${{ steps.version.outputs.version }}
            GPU_FAMILY="intel"
            TOOLS=quay.io/fedora-atomic-desktops-sealed/tools:${{ matrix.release }}
          extra-args: |
            --security-opt=label=disable
            --volume ${{ github.workspace }}:/run/src
            --secret=id=secureboot_key,src=/tmp/keys/key
            --secret=id=secureboot_crt,src=/tmp/keys/crt

      - name: "Build Intel UKI container image"
        uses: redhat-actions/buildah-build@v2
        if: false
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-intel
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}
          containerfiles: Containerfile.uki
          oci: true
          build-args: |
            BASE=${{ env.REPO_NAME }}/${{ matrix.variant }}-base:${{ matrix.release }}.${{ steps.version.outputs.version }}
            KERNEL=${{ env.REPO_NAME }}/${{ matrix.variant }}-kernel:${{ matrix.release }}.${{ steps.version.outputs.version }}
            GPU_FAMILY="intel"
            TOOLS=quay.io/fedora-atomic-desktops-sealed/tools:${{ matrix.release }}
          extra-args: |
            --security-opt=label=disable
            --volume ${{ github.workspace }}:/run/src
            --secret=id=secureboot_key,src=/tmp/keys/key
            --secret=id=secureboot_crt,src=/tmp/keys/crt

      - name: "Build AMD UKI container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-amd
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}
          containerfiles: Containerfile.uki
          oci: true
          build-args: |
            BASE=${{ env.REPO_NAME }}/${{ matrix.variant }}-base:${{ matrix.release }}.${{ steps.version.outputs.version }}
            KERNEL=${{ env.REPO_NAME }}/${{ matrix.variant }}-kernel:${{ matrix.release }}.${{ steps.version.outputs.version }}
            GPU_FAMILY="amd"
            TOOLS=${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/tools:${{ matrix.release }}
          extra-args: |
            --security-opt=label=disable
            --volume ${{ github.workspace }}:/run/src
            --secret=id=secureboot_key,src=/tmp/keys/key
            --secret=id=secureboot_crt,src=/tmp/keys/crt

      - name: "Build NVIDIA UKI container image"
        uses: redhat-actions/buildah-build@v2
        if: false
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-nvidia
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}
          containerfiles: Containerfile.uki
          oci: true
          build-args: |
            BASE=${{ env.REPO_NAME }}/${{ matrix.variant }}-base:${{ matrix.release }}.${{ steps.version.outputs.version }}
            KERNEL=${{ env.REPO_NAME }}/${{ matrix.variant }}-kernel:${{ matrix.release }}.${{ steps.version.outputs.version }}
            GPU_FAMILY="nvidia"
            TOOLS=quay.io/fedora-atomic-desktops-sealed/tools:${{ matrix.release }}
          extra-args: |
            --security-opt=label=disable
            --volume ${{ github.workspace }}:/run/src
            --secret=id=secureboot_key,src=/tmp/keys/key
            --secret=id=secureboot_crt,src=/tmp/keys/crt

      - name: "Cleanup Secure Boot signing key"
        if: always()
        run: rm -vrf /tmp/keys

      - name: "Setup cosign"
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'

      - name: "Push generic image to Container Registry (ghcr.io)"
        uses: redhat-actions/push-to-registry@v2
        id: push
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}
          registry: ${{ env.REGISTRY_GHCR }}
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}

      - name: "Push Intel image to Container Registry (ghcr.io)"
        uses: redhat-actions/push-to-registry@v2
        id: push_intel
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-intel
          registry: ${{ env.REGISTRY_GHCR }}
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}

      - name: "Push AMD image to Container Registry (ghcr.io)"
        uses: redhat-actions/push-to-registry@v2
        id: push_amd
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-amd
          registry: ${{ env.REGISTRY_GHCR }}
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}

      - name: "Push NVIDIA image to Container Registry (ghcr.io)"
        uses: redhat-actions/push-to-registry@v2
        id: push_nvidia
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-nvidia
          registry: ${{ env.REGISTRY_GHCR }}
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}

      - name: "Sign generic container image (ghcr.io)"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/${{ matrix.variant }}@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign Intel container image (ghcr.io)"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-intel@${{ steps.push_intel.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign AMD container image (ghcr.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y ${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-amd@${{ steps.push_amd.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false

      - name: "Sign NVIDIA container image (ghcr.io)"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-nvidia@${{ steps.push_nvidia.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Login to Container Registry (quay.io)"
        uses: redhat-actions/podman-login@v1
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        with:
          registry: ${{ env.REGISTRY_QUAY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}

      - name: "Push generic image to Container Registry (quay.io)"
        uses: redhat-actions/push-to-registry@v2
        id: push_quay_io
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}
          registry: ${{ env.REGISTRY_QUAY }}
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}

      - name: "Push Intel image to Container Registry (quay.io)"
        uses: redhat-actions/push-to-registry@v2
        id: push_quay_io_intel
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-intel
          registry: ${{ env.REGISTRY_QUAY }}
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}

      - name: "Push AMD image to Container Registry (quay.io)"
        uses: redhat-actions/push-to-registry@v2
        id: push_quay_io_amd
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-amd
          registry: ${{ env.REGISTRY_QUAY }}
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}

      - name: "Push NVIDIA image to Container Registry (quay.io)"
        uses: redhat-actions/push-to-registry@v2
        id: push_quay_io_nvidia
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-nvidia
          registry: ${{ env.REGISTRY_QUAY }}
          tags: ${{ matrix.release }}.${{ steps.version.outputs.version }} ${{ matrix.release }}

      - name: "Sign generic container image (quay.io)"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_QUAY }}/${{ env.REPO_NAME }}/${{ matrix.variant }}@${{ steps.push_quay_io.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign Intel container image (quay.io)"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_QUAY }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-intel@${{ steps.push_quay_io_intel.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign AMD container image (quay.io)"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_QUAY }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-intel@${{ steps.push_quay_io_amd.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign NVIDIA container image (quay.io)"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        if: false
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_QUAY }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-intel@${{ steps.push_quay_io_nvidia.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
